# THIS IS EXPERIMENTAL
# the config file schema may change at any time

style:
    tag:
        color: yellow
        width_percentage: 26
        min_width: 20
    comment:
        color: green
        width_percentage: 42
        min_width: 45
    snippet:
        color: magenta

finder:
    command: fzf

# cheats:
# paths:
# - /path/to/some/dir
# - /path/to/another/dir

shell:
    command: bash
