[icons]
name = 'none'
[icons.overrides]
backlight_full = "â˜¼ "
backlight_partial3 = "â˜¼ "
backlight_partial2 = "â˜¼ "
backlight_partial1 = "â˜€ "
backlight_empty = "â˜€ "
volume_half = "ğŸ”‰ "
volume_full = "ğŸ”Š "
volume_muted = "ğŸ”ˆ "

[theme]
name = "modern"

[[block]]
block = "keyboard_layout"
driver = "localebus"

[[block]]
block = "custom"
interval = 3600
command = ''' echo ğŸ¸ $(~/bin/couple.sh birthday) '''

[[block]]
block = "custom"
interval = 3600
command = '''echo â¤ $(~/bin/couple.sh relationship) '''

[[block]]
block = "sound"
format = "{output_name} {volume}"

[[block]]
block = "backlight"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"
