# inserts a blank line between shell prompts
add_newline = true

format = """
[::](fg:cyan) $kubernetes $rust $golang $helm
[â”Œâ”€](fg:white) $username @ $hostname $directory $git_branch $git_status $git_state
[â””â”€](fg:white)$character"""

[helm]
format = " [$symbol($version )]($style)"
style = "fg:#a9a9a9"

[hostname]
format = "[$hostname]($style)"
ssh_only = false
style = "bold fg:#00bfff"

[username]
show_always = true
format = "[$user]($style)"

[character]
success_symbol = "[â—‹](bold fg:#adff2f) "
error_symbol = "[âœ—](bold fg:#ff4d4d) "

[directory]
style = "fg:#ffa500"
home_symbol = "ğŸ "

[golang]
style = "fg:#00add8"
format = "[$symbol$version]($style)"

[git_branch]
style = "fg:#a500ff"
format = "[$symbol$branch]($style)"

[kubernetes]
disabled = false
style = "fg:#00bfff"
format = '[$symbol]($style)[\(]($style)[$context](fg:#9ae5ff) [$namespace\)]($style)'
